[package]
name = "adapters"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
ports = { path = "../ports" }
common = { path = "../common" }
contracts-kafka = { path = "../contracts-kafka" }
