[package]
name = "adapters"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
ports = { path = "../ports" }
observability = { path = "../observability" }
contracts-kafka = { path = "../contracts-kafka" }
