[workspace]
members = [
  "crates/domain",
  "crates/ports",
  "crates/application",
  "crates/adapters",
  "crates/contracts-kafka",
  "crates/common",
  "crates/bootstrap",
  "crates/tests",
]
resolver = "2"
