[package]
name = "application"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
domain = { path = "../domain" }
ports = { path = "../ports" }
observability = { path = "../observability" }

